### PR TITLE
Add excluded topics setting

### PR DESCRIPTION
**Pull request by angusmcleod**
Adds a site setting that lets you exclude topics from the sitemap via a regex filter on the title.

### CODE REVIEW

**Comment by SamSaffron** [comment]
Why would this be used if the crawler can still find it anyway? Seems like a better solution would be to hide the problem topics? Put them in a secure category?

**Comment by ClubicTech** [comment]
Hello, 
I need this feature.
When we have pages with a meta or header robots with noindex. 
Ideally Discourse should manage rules of meta robots and exclude from the sitemap. 
But it doesn't exist, so a nginx + sitemap exclusion does the job.

**Comment by SamSaffron** [comment]
I am still not following at all, so you are monkey patching discourse to add headers to random pages? If so why not monkey patch this plugin at the same time?

**Comment by ClubicTech** [comment]
I not use plugin, juste use Nginx config with url rules (on url i have topic title) for add header "X-Robots-Tag: noindex".
exemple nginx config:
```
    location ~/t/comment-(.*)$ {
	add_header X-Robots-Tag "noindex";
    }
```

**Comment by angusmcleod** [comment]
@SamSaffron For context the problem [Clubic](https://www.clubic.com/forum) have is that, for SEO purposes, they want to hide set of old topics from search indexing without hiding them from users. It's not dissimilar to situations like [this](https://meta.discourse.org/t/seo-for-thin-content-or-modify-meta-tags/125362). It's currently possible to add these topics to the robots.txt file, but not possible to exclude them from the sitemap. Sorry, probably should have led with that.

**Comment by SamSaffron** [comment]
I feel like the correct approach here is a different plugin, not regexes applied to the sitemap plugin. 

I don't really see this in scope for the sitemap plugin.

**Pull request closed without merging**
